[package]
name = "guessing"
version = "0.1.1"
authors = ["Alexey Morkovin <3dguru@inbox.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand='0.3.0'
