name: Rust-linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Installing cargo-deb
      run: cargo install cargo-deb
    - name: Creating a deb package
      run: cargo-deb
          
    # Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: guessing.deb
        path: target/debian/guessing_0.1.1_amd64.deb
        
    # Create release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: tagv1.1-linux
          release_name: Release v1.1-linux ${{ github.ref }}
          draft: false
          prerelease: false
          
    # Upload binaries to release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/debian/guessing_0.1.1_amd64.deb
        asset_name: target/debian/guessing_0.1.1_amd64.deb
        tag: tagv1.1-linux
        overwrite: true
    #- name: Publishing
    #  run: curl -T target/debian/guessing_0.1.1_amd64.deb -umadfisht3:${{ secrets.API_KEY }} https://api.bintray.com/content/madfisht3/guessing/guessing/1/guessing_0.1.1_amd64.deb
